---
# defaults file for roles/lab.hostname
connect_timeout:
msg: "Reboot the machine after changing its hostname"
post_reboot_delay: 0
pre_reboot_delay: 0
reboot_timeout: 600
test_command: whoami
hostname: "{{ inventory_hostname }}"

